### ISSUE TITLE
08/05/2020

### ISSUE THREAD

**Issue by Victorgonbu** [carlos-ssh/mint-form#3]
Some recommendations:
-to fix button positioning, try to use a fixed position, and play a little bit with the spacing between bottom and text.
-try to fix your icons, instead of being a whole image for it, try to put just the icon image next to maybe a tag.
-you will have to use stylelint for you to fix all lint error, you will need node.js for that.
-and maybe you forgot to turn on a stickler on your repository.

Thanks for sharing!

-

**Comment by carlos-ssh** [comment]
thanks for the suggestions we are working to give a better service.
